<?php $title = "Introduction"; include("header.html"); ?>
  <h1>Introduction</h1>

  <p><span class="decorative">W</span>illiam Howlett comes from Wexford, Ireland and studied medicine at University College Dublin, graduating in 1970. After training as a general physician and in tropical medicine he first worked in Africa with Christian Aid in 1980-81 in a famine in Northern Uganda. He then spent over 9 years (1983-1992) working as a physician at Kilimanjaro Christian Medical Centre (<span class="definition" title="Kilimanjaro Christian Medical Centre">KCMC</span>) in Northern Tanzania, supported by Irish aid overseas (<span class="definition" title="Association for Personnel Service Overseas">APSO</span>). During this time he helped document the arrival of <span class="definition" title="Acquired Immunodeficiency Syndrome">AIDS</span>, its clinical description and initiate its prevention.</p>

  <p>Returning from Africa in 1992, he completed a PhD in tropical neurology at the Centre for International Health, Bergen, Norway in 1995; he published original research on the neurological complications of AIDS and konzo, in particular the role played in konzo by high dietary exposure to cyanide from cassava roots. He later retrained as neurologist in UK before joining the <span class="definition" title="National Health Service">NHS</span> as a consultant neurologist.</p>

  <p>In 2006 Dr Howlett returned to <span class="definition" title="Kilimanjaro Christian Medical Centre">KCMC</span> to work in patient care, teaching and research. He is a founder member of the newly formed Tanzania Neuroscience Association (TNA) which has been recognized by the World Federation of Neurology. Its main aim is to develop neurological services within Tanzania and East Africa. In 2010 he was awarded the Distinguished Graduate Award by the Medical Graduates Association of <span class="definition" title="University College Dublin">UCD</span> in acknowledgment of his contribution to medicine in Tanzania. He is an internationally recognized leader in <span class="definition" title="Acquired Immunodeficiency Syndrome">AIDS</span> and tropical neurology, and has published extensively in scientific journals.</p>

  <p>Dr Howlett is involved in teaching undergraduate and postgraduate students. One of the main aims of his work in Africa is to develop teaching material specific for Africa. With that in mind he has written and published in 2012 a highly acclaimed textbook "Neurology in Africa". It is now considered an essential textbook for teaching neurology for students and doctors in Africa. It is available free online to download. He has also recently produced a teaching video for students demonstrating how to conduct a neurological examination. </p>

  <p>Dr Howlett works to improve patient care and health education in Africa. An "Africa trust fund" has been set up to support his work in Tanzania and is administered by a solicitor in Wexford. The target is &pound;30,000 per year. Contributions to the fund from individuals and institutions are welcome.</p>

<?php include("footer.html"); ?>
